{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $release_service := .Release.Service }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  name: {{ template "cronjob.name" $ }}
  {{- with $.Values.annotations }}
  annotations:
{{ toYaml . | indent 6}}
  {{- end }}
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    release: {{ $release_name }}
    heritage: {{ $release_service }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $release_name }}
            release: {{ $release_name }}
            cron: {{ $job.name }}
            {{- if $job.podLabels }}
{{ toYaml $job.podLabels | indent 12 }}
            {{- end }}
        spec:
{{ toYaml $job.spec | indent 10 }}
{{- end }}
