# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # first cron
  - name: hello-world
    podLabels:
      hello: world
      bonjour: monde
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    spec:
      containers:
      - name: ct-1
        image: hello-world:latest
      restartPolicy: OnFailure
