kind: NetworkPolicy
apiVersion: {{ template "networkpolicy.apiVersion" . }}
metadata:
  name: {{ template "networkpolicy.name" . }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}
  labels:
    app: {{ template "networkpolicy.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.podSelector }}
  podSelector:
{{ toYaml . | indent 7 }}
{{- end }}
{{- if or .Values.ingressRules .Values.egressRules }}
  policyTypes:
{{- if .Values.ingressRules }}
    - Ingress
{{- end }}
{{- if .Values.egressRules }}
    - Egress
{{- end }}
{{- end }}
{{- with .Values.egressRules }}
  egress:
{{-  range . }}
    - {{ with .selectors -}}
      to:
{{ toYaml . | indent 7 }}
{{- end }}
      ports:
{{ toYaml .ports | indent 9 }}
{{- end }}
{{- end }}
{{- with .Values.ingressRules }}
  ingress:
{{-  range . }}
    - {{ with .selectors -}}
      from:
{{ toYaml . | indent 7 }}
{{- end }}
      ports:
{{ toYaml .ports | indent 9 }}
{{- end }}
{{- end }}
